### ISSUE TITLE
Move off netlify

### ISSUE THREAD

**Issue by Eh2406** [pubgrub-rs/guide#10]
Move the website off netlify onto something else. Cloud flare static pages, or git-hub pages or something.

https://github.com/pubgrub-rs/pubgrub/issues/192#issuecomment-2010448421

> Coincidentaly, last month I went cleaning up all my netlify websites and the only one I have left is the one for pubgrub guide. I also want to clean this one as I don't want any surprised invoice. I've been testing cloudflare that works quite well! So I'd like to move the guide to a cloudflare static website, and also would like to not have it handled by my personal account, even though it's less risky for me than netlify. So I want to dust off a bit all these docs things.

**Comment by mpizenberg** [comment]
Done in #12

**Comment by mpizenberg** [comment]
![image](https://github.com/pubgrub-rs/guide/assets/2905865/6d17ef33-c758-4d32-bd81-27f9cc98ef54)

The GH action for Cloudflare prod and per-branch preview builds seems to be working weel
